const mongoose = require("mongoose");
const Product = require("../model/product");
const Shop = require("../model/shop");
const Category = require("../model/category");
const Brands = require("../model/brands");
const axios = require("axios");
const casual = require("casual");

mongoose.connect(
  "mongodb+srv://yusasive:yusasive@yusasive.dwzc5vv.mongodb.net/yusasive",
  {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  }
);

const getRandomElement = (array) => {
  const randomIndex = Math.floor(Math.random() * array.length);
  return array[randomIndex];
};

const generateProductData = async (shops, categories, brands) => {
  const imageUrl = await axios.get(
    "https://source.unsplash.com/random/400x400"
  );

  const productNames = [
    "Smartphone",
    "Laptop",
    "Headphones",
    "Digital Camera",
    "Fitness Tracker",
    "Coffee Maker",
    "Bluetooth Speaker",
    "Wireless Mouse",
    "External Hard Drive",
    "Smart TV",
    "Tablet",
    "Gaming Console",
    "Air Purifier",
    "Robot Vacuum",
    "Electric Toothbrush",
    "Fitness Band",
    "Portable Charger",
    "Wireless Earbuds",
    "Desk Chair",
    "Standing Desk",
    "Gaming Laptop",
    "Coffee Grinder",
    "Blender",
    "Microwave Oven",
    "LED Desk Lamp",
    "Bluetooth Earphones",
    "Backpack",
    "Water Bottle",
    "Gaming Monitor",
    "USB Flash Drive",
    "Desk Organizer",
    "Wireless Keyboard",
    "Smartwatch",
    "Drones",
    "Car Vacuum Cleaner",
    "Mouse Pad",
    "Solar Charger",
    "Portable Projector",
    "Wireless Router",
    "Soundbar",
    "Printer",
    "Air Fryer",
    "Security Camera",
    "Graphics Card",
    "Noise-Canceling Headphones",
    "External SSD",
    "Smart Thermostat",
    "Baby Monitor",
    "Wireless Charging Pad",
    "Projector Screen",
    "Mini Fridge",
    "Smart Doorbell",
    "Memory Foam Pillow",
    "Bluetooth Mouse",
    "Wireless Gaming Mouse",
    "Desk Fan",
    "Car Phone Holder",
    "Digital Scale",
    "Wireless Charging Stand",
    "USB Hub",
    "Smart Light Bulbs",
    "Dash Cam",
    "External Blu-ray Drive",
    "Fitness Mat",
    "Gaming Chair",
    "Desk Plant",
    "LED Strip Lights",
    "Wireless Presenter",
    "Coffee Table",
    "Ergonomic Keyboard",
    "Portable Monitor",
    "AirPods Case",
    "Gaming Mouse Pad",
    "USB-C Docking Station",
    "Wireless Security System",
    "Power Strip",
    "Portable Ice Maker",
    "Pet Camera",
    "Bluetooth Keyboard",
    "Electric Scooter",
    "Gaming Headset",
    "Smart Mirror",
    "Wireless Car Charger",
    "Bluetooth FM Transmitter",
    "Smart Backpack",
    "USB Microphone",
    "Tea Infuser",
    "Air Mattress",
    "Wireless Barcode Scanner",
    "Touchscreen Gloves",
    "Bluetooth Beanie",
    "Mini Projector",
    "Smart Home Hub",
    "Smart Plug",
    "Electric Kettle",
    "Digital Notepad",
    "Laser Printer",
    "Wireless Charging Mouse Pad",
    "Gaming Desk",
    "Solar Powered Lights",
    "Wi-Fi Range Extender",
    "Desk Exercise Bike",
    "Smart Lock",
    "Bluetooth Shower Speaker",
    "Automatic Pet Feeder",
    "Collapsible Water Bottle",
    "Gaming Glasses",
    "Wireless HDMI Transmitter",
    "LED Desk Clock",
    "Heated Blanket",
    "Fitness Tracker Watch",
    "Portable Espresso Maker",
    "Smart Refrigerator",
    "Massage Gun",
    "Robot Lawn Mower",
    "LED Vanity Mirror",
    "Smart Garden",
    "Gaming Keyboard",
    "USB Desk Fan",
    "Wireless Charging Backpack",
    "Bluetooth Sunglasses",
    "Solar-Powered Charger",
    "Fitness Resistance Bands",
    "Car Air Purifier",
    "Mini Air Cooler",
    "Desk Hammock",
    "Gaming Mouse Bungee",
    "Wireless Charging Desk Pad",
    "UV-C Sanitizer Wand",
    "Bluetooth Trackers",
    "Solar Power Bank",
    "Smart Alarm Clock",
    "Wireless Charging Alarm Clock",
    "Smart Glasses",
    "Portable UV-C Sterilizer",
    "Gaming Console Stand",
    "Digital Drawing Tablet",
    "Selfie Ring Light",
    "LED Gaming Mouse",
    "Portable Bluetooth Printer",
    "Desk Cable Organizer",
    "Gaming Mouse Pouch",
    "Car Desk",
    "Wireless Charging Floor Lamp",
    "Smart Light Switch",
    "Solar Garden Lights",
    "Gaming Glasses",
    "Desk Drawer Organizer",
    "Fitness Tracker Ring",
    "Portable Neck Fan",
    "Wireless Charging Pen Holder",
    "Bluetooth Bookshelf Speakers",
    "Gaming Mouse Mat",
    "Air Purifying Bag",
    "Solar-Powered Lantern",
    "Wireless Charging Desk Lamp",
    "Mini Desk Vacuum",
    "Bluetooth Karaoke Microphone",
    "Smart Umbrella",
    "Desk Foot Hammock",
    "Gaming Console Shelf",
    "Wireless Charging Mouse Mat",
    "Bluetooth Audio Adapter",
    "Smart Ceiling Fan",
    "Solar String Lights",
    "Gaming Desk Accessories",
    "Wireless Charging Desk Organizer",
    "Bluetooth Game Controller",
    "LED Gaming Desk",
    "Smart Mug",
    "Portable Bluetooth Keyboard",
    "Desk Chair Cushion",
    "Gaming Mouse Grip",
    "Wireless Charging Bedside Lamp",
    "Bluetooth Trackball Mouse",
    "Smart Notebook",
    "Gaming Laptop Cooling Pad",
    "Wireless Charging Nightstand",
    "Desk Drawer Dividers",
    "Bluetooth Fitness Tracker",
    "Smart Plugs with USB",
    "Gaming Desk Mat",
    "Wireless Charging Desk Clock",
    "Bluetooth Barcode Scanner",
    "Smart Water Bottle",
    "Desk Cable Clips",
    "Wireless Charging Desk Fan",
    "Gaming Console Skin",
    "Bluetooth Sleep Mask",
    "Desk Cable Grommet",
    "Wireless Charging Desk Accessories",
    "Bluetooth Desk Fan",
    "Smart Light Strip",
    "Gaming Mouse Holder",
    "Wireless Charging Desk Shelf",
    "Bluetooth Wireless Ear Muffs",
    "Smart Pet Feeder",
    "Desk Chair Armrest Covers",
    "Wireless Charging Desk Stand",
    "Bluetooth Portable Printer",
    "Smart Dog Collar",
    "Gaming Laptop Stand",
    "Wireless Charging Desk Tray",
    "Bluetooth Folding Keyboard",
    "Smart Wi-Fi Router",
    "Desk Cable Management Box",
    "Wireless Charging Desk Tidy",
    "Bluetooth Computer Glasses",
    "Smart Bike Lock",
    "Gaming Chair Cover",
    "Wireless Charging Desk Table",
    "Bluetooth Yoga Mat",
    "Smart Grill Thermometer",
    "Desk Chair Armrest Pads",
    "Wireless Charging Desk Lamp Stand",
    "Bluetooth Mechanical Keyboard",
    "Smart Refrigerator Camera",
    "Gaming Desk Shelf",
    "Wireless Charging Desk Cup Holder",
    "Bluetooth Desk Organizer",
    "Smart Electric Toothbrush",
    "Gaming Chair Mat",
    "Wireless Charging Desk Drawer",
    "Bluetooth Desk Clock",
    "Smart Coffee Maker",
    "Gaming Mouse Cable Holder",
    "Wireless Charging Desk Lamp Base",
    "Bluetooth Desk Speaker",
    "Smart Light Socket",
    "Gaming Desk Lamp",
    "Wireless Charging Desk Lamp Organizer",
    "Bluetooth Desk Lamp",
    "Smart Watering System",
    "Gaming Desk Accessories Kit",
    "Wireless Charging Desk Lamp Shelf",
    "Bluetooth Desk Lamp with Speaker",
    "Smart Wine Opener",
    "Gaming Desk RGB Lights",
    "Wireless Charging Desk Lamp Pad",
    "Bluetooth Desk Lamp with Wireless Charger",
    "Smart Light Bulb",
    "Gaming Desk Mouse Pad",
    "Wireless Charging Desk Lamp Tray",
    "Bluetooth Desk Lamp with USB Port",
    "Smart Coffee Mug",
    "Gaming Chair Lumbar Pillow",
    "Wireless Charging Desk Lamp Cup Holder",
    "Bluetooth Desk Fan with Light",
    "Smart Humidifier",
    "Gaming Chair Armrest Pads",
    "Wireless Charging Desk Lamp with Organizer",
    "Bluetooth Desk Fan with Speaker",
    "Smart Air Purifier",
    "Gaming Chair Armrest Covers",
    "Wireless Charging Desk Lamp with Shelf",
    "Bluetooth Desk Fan with USB Port",
    "Smart Weight Scale",
    "Gaming Chair Armrest Cushion",
    "Wireless Charging Desk Lamp with Clock",
    "Bluetooth Desk Fan with Wireless Charger",
    "Smart Temperature Control Mug",
    "Gaming Desk Cable Management",
    "Wireless Charging Desk Lamp with Pen Holder",
    "Bluetooth Desk Speaker Lamp",
    "Smart Indoor Garden",
    "Gaming Chair Armrest Replacement",
    "Wireless Charging Desk Lamp with Tray",
    "Bluetooth Desk Organizer with Wireless Charger",
    "Smart Mirror with Lights",
    "Gaming Chair Armrest Extension",
    "Wireless Charging Desk Lamp with Cup Holder",
    "Bluetooth Desk Organizer with USB Port",
    "Smart Clothes Hanger",
    "Gaming Chair Armrest Tray",
    "Wireless Charging Desk Lamp with RGB Lights",
    "Bluetooth Desk Organizer with Speaker",
    "Smart Trash Can",
    "Gaming Chair Armrest Shelf",
    "Wireless Charging Desk Lamp with Drawer",
    "Bluetooth Desk Organizer with Clock",
    "Smart Plant Pot",
    "Gaming Chair Armrest Table",
    "Wireless Charging Desk Lamp with USB Port",
    "Bluetooth Desk Organizer with Pen Holder",
    "Smart Air Conditioner",
    "Gaming Chair Armrest Shelf Tray",
    "Wireless Charging Desk Lamp with Wireless Charger",
    "Bluetooth Desk Organizer with Wireless Charger",
    "Smart Toothbrush Holder",
    "Gaming Chair Armrest Shelf Organizer",
    "Wireless Charging Desk Lamp with Desk Organizer",
    "Bluetooth Desk Lamp with Clock",
    "Smart Soap Dispenser",
    "Gaming Chair Armrest Shelf with USB Port",
    "Wireless Charging Desk Lamp with Desk Tray",
    "Bluetooth Desk Lamp with Pen Holder",
    "Smart Shoe Rack",
    "Gaming Chair Armrest Shelf with Wireless Charger",
    "Wireless Charging Desk Lamp with Desk Shelf",
    "Bluetooth Desk Lamp with Shelf",
    "Smart Dog Bed",
    "Gaming Chair Armrest Shelf with RGB Lights",
    "Wireless Charging Desk Lamp with Desk Clock",
    "Bluetooth Desk Lamp with Tray",
    "Smart Plant Stand",
    "Gaming Chair Armrest Shelf with USB Port",
    "Wireless Charging Desk Lamp with Desk Organizer",
    "Bluetooth Desk Lamp with USB Port",
    "Smart Pet Door",
    "Gaming Chair Armrest Shelf with Desk Tray",
    "Wireless Charging Desk Lamp with Desk Tidy",
    "Bluetooth Desk Lamp with Wireless Charger",
    "Smart Pet Fountain",
    "Gaming Chair Armrest Shelf with Desk Shelf",
    "Wireless Charging Desk Lamp with Desk Stand",
    "Bluetooth Desk Lamp with Wireless Charger and Organizer",
    "Smart Pet Tracker",
    "Gaming Chair Armrest Shelf with Desk Clock",
    "Wireless Charging Desk Lamp with Desk Accessories",
    "Bluetooth Desk Lamp with Wireless Charger and Clock",
    "Smart Pet Feeding Bowl",
    "Gaming Chair Armrest Shelf with Desk Organizer",
    "Wireless Charging Desk Lamp with Desk Cup Holder",
    "Bluetooth Desk Lamp with Wireless Charger and Pen Holder",
    "Smart Pet Treat Dispenser",
    "Gaming Chair Armrest Shelf with Desk Shelf and USB Port",
    "Wireless Charging Desk Lamp with Desk Lamp",
    "Bluetooth Desk Lamp with Wireless Charger and Tray",
    "Smart Pet Doorbell",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger",
    "Wireless Charging Desk Lamp with Desk Organizer and Shelf",
    "Bluetooth Desk Lamp with Wireless Charger and USB Port",
    "Smart Pet Litter Box",
    "Gaming Chair Armrest Shelf with Desk Shelf and RGB Lights",
    "Wireless Charging Desk Lamp with Desk Organizer and USB Port",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Tray",
    "Smart Pet Camera",
    "Gaming Chair Armrest Shelf with Desk Shelf and USB Port and RGB Lights",
    "Wireless Charging Desk Lamp with Desk Organizer and Clock",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer",
    "Smart Pet Collar",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and RGB Lights",
    "Wireless Charging Desk Lamp with Desk Organizer and Shelf",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer and USB Port",
    "Smart Pet Tracker Collar",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and USB Port",
    "Wireless Charging Desk Lamp with Desk Organizer and Tray",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer and Shelf",
    "Smart Pet Bowtie",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and USB Port and RGB Lights",
    "Wireless Charging Desk Lamp with Desk Organizer and Wireless Charger",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer and Tray",
    "Smart Pet Feeding Mat",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and USB Port and Desk Tray",
    "Wireless Charging Desk Lamp with Desk Organizer and Wireless Charger and Shelf",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer and USB Port and Shelf",
    "Smart Pet GPS Tracker",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and USB Port and Desk Organizer",
    "Wireless Charging Desk Lamp with Desk Organizer and Wireless Charger and Shelf and RGB Lights",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer and USB Port and Tray",
    "Smart Pet Water Dispenser",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and USB Port and Desk Organizer and RGB Lights",
    "Wireless Charging Desk Lamp with Desk Organizer and Wireless Charger and Shelf and USB Port",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer and Wireless Charger",
    "Smart Pet Food Bowl",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and USB Port and Desk Organizer and Wireless Charger",
    "Wireless Charging Desk Lamp with Desk Organizer and Wireless Charger and Shelf and Desk Tray",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer and Wireless Charger and Organizer",
    "Smart Pet Food Mat",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and USB Port and Desk Organizer and Shelf",
    "Wireless Charging Desk Lamp with Desk Organizer and Wireless Charger and Shelf and Pen Holder",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer and Wireless Charger and Shelf",
    "Smart Pet Treat Holder",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and USB Port and Desk Organizer and Shelf and RGB Lights",
    "Wireless Charging Desk Lamp with Desk Organizer and Wireless Charger and Shelf and USB Port and RGB Lights",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer and Wireless Charger and Shelf and RGB Lights",
    "Smart Pet Paw Cleaner",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and USB Port and Desk Organizer and Shelf and Wireless Charger",
    "Wireless Charging Desk Lamp with Desk Organizer and Wireless Charger and Shelf and USB Port and Desk Tray",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer and Wireless Charger and Shelf and USB Port",
    "Smart Pet Nail Grinder",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and USB Port and Desk Organizer and Shelf and Wireless Charger and RGB Lights",
    "Wireless Charging Desk Lamp with Desk Organizer and Wireless Charger and Shelf and USB Port and Wireless Charger",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer and Wireless Charger and Shelf and USB Port and Shelf",
    "Smart Pet Toothbrush",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and USB Port and Desk Organizer and Shelf and Wireless Charger and USB Port",
    "Wireless Charging Desk Lamp with Desk Organizer and Wireless Charger and Shelf and USB Port and Shelf and RGB Lights",
    "Bluetooth Desk Lamp with Wireless Charger and Desk Organizer and Wireless Charger and Shelf and USB Port and Shelf and RGB Lights",
    "Smart Pet Toothpaste",
    "Gaming Chair Armrest Shelf with Desk Shelf and Wireless Charger and USB Port and Desk Organizer and Shelf and Wireless Charger and USB Port and RGB Lights",
    "Wireless Charging Desk",
    "Smartphone",
    "Laptop",
    "Headphones",
    "Digital Camera",
    "Fitness Tracker",
    "Coffee Maker",
    "Bluetooth Speaker",
    "Wireless Mouse",
    "External Hard Drive",
    "Smart TV",
    "Tablet",
    "Gaming Console",
    "Printer",
    "Monitor",
    "Desk Chair",
    "Desk Lamp",
    "Backpack",
    "Power Bank",
    "Wireless Earbuds",
    "Drones",
    "Robot Vacuum",
    "Blender",
    "Toaster",
    "Microwave",
    "Refrigerator",
    "Washing Machine",
    "Electric Toothbrush",
    "Smart Thermostat",
    "Air Purifier",
    "Coffee Table",
    "Sofa",
    "Area Rug",
    "Bed Frame",
    "Mattress",
    "Pillow",
    "Bedside Table",
    "Alarm Clock",
    "Bookshelf",
    "Wall Clock",
    "Plant Pot",
    "Sunglasses",
    "Running Shoes",
    "Backpack",
    "Handbag",
    "Watch",
    "Bracelet",
    "Necklace",
    "Earrings",
    "Wallet",
    "Dress",
    "T-Shirt",
    "Jeans",
    "Jacket",
    "Hoodie",
    "Sweater",
    "Sneakers",
    "Sandals",
    "Umbrella",
    "Luggage",
    "Towel",
    "Blanket",
    "Candles",
    "Essential Oils",
    "Yoga Mat",
    "Resistance Bands",
    "Foam Roller",
    "Weighted Blanket",
    "Puzzle",
    "Board Game",
    "Video Game",
    "Keyboard",
    "Mouse",
    "Desk Organizer",
    "Notebook",
    "Pen Set",
    "Water Bottle",
    "Back Support Pillow",
    "Shower Curtain",
    "Towel Set",
    "Cookware Set",
    "Cutlery Set",
    "Dining Table",
    "Dining Chairs",
    "Bar Stools",
    "Food Processor",
    "Air Fryer",
    "Crock Pot",
    "Blender",
    "Coffee Grinder",
    "Teapot",
    "Tea Set",
    "Wine Glasses",
    "Cocktail Shaker",
    "Pots and Pans Set",
    "Bakeware Set",
    "Dinnerware Set",
    "Flatware Set",
    "Bath Towels",
    "Hand Towels",
    "Face Masks",
    "Hair Dryer",
    "Straightener",
    "Curling Iron",
    "Makeup Mirror",
    "Skincare Set",
    "Cologne",
    "Perfume",
    "Shampoo",
    "Conditioner",
    "Toothpaste",
    "Floss",
    "Sunscreen",
    "Lip Balm",
    "Candles",
    "Essential Oils",
    "Oil Diffuser",
    "Throw Pillow",
    "Area Rug",
    "Curtains",
    "Wall Art",
    "Plant",
    "Coffee Table Books",
    "Mirror",
    "Vase",
    "Coasters",
    "Cutting Board",
    "Placemats",
    "Napkin Rings",
    "Candle Holder",
    "Wine Rack",
    "Fire Pit",
    "Outdoor Furniture",
    "Grill",
    "Garden Hose",
    "Lawn Mower",
    "Hammock",
    "Fishing Rod",
    "Camping Tent",
    "Sleeping Bag",
    "Backpack",
    "Portable Grill",
    "Cooler",
    "Binoculars",
    "Outdoor Lantern",
    "First Aid Kit",
    "Bug Spray",
    "Picnic Basket",
    "Frisbee",
    "Bike",
    "Helmet",
    "Rollerblades",
    "Skateboard",
    "Snowboard",
    "Ski Gear",
    "Winter Jacket",
    "Snow Boots",
    "Thermal Socks",
    "Snow Gloves",
    "Ice Skates",
    "Sled",
    "Snowshoes",
    "Tent",
    "Sleeping Bag",
    "Backpack",
    "Flashlight",
    "Multi-Tool",
    "Survival Kit",
    "Water Purifier",
    "Camping Stove",
    "Hiking Boots",
    "Binoculars",
    "Compass",
    "Headlamp",
    "Map",
    "Outdoor Clothing",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Hiking Poles",
    "Water Bottle",
    "Trail Mix",
    "Sunscreen",
    "Bug Spray",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Camping Chair",
    "Portable Grill",
    "Cooler",
    "Hammock",
    "Water Purifier",
    "First Aid Kit",
    "Sleeping Bag",
    "Tent",
    "Backpack",
    "Lantern",
    "Cooking Stove",
    "Sleeping Pad",
    "Hiking Boots",
    "Water Bottle",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking Boots",
    "Water Bottle",
    "Trail Mix",
    "Map",
    "Compass",
    "Headlamp",
    "Backpack",
    "Sleeping Bag",
    "Tent",
    "Hiking",
  ];

  const productData = {
    name: getRandomElement(productNames),
    description: casual.text,
    categories: [getRandomElement(categories)._id],
    tags: "Product tags",
    originalPrice: Math.floor(Math.random() * 100) + 50,
    discountPrice: Math.floor(Math.random() * 50),
    stock: Math.floor(Math.random() * 50) + 10,
    images: [
      {
        public_id: `product-image-${Date.now()}`,
        url: imageUrl.request.res.responseUrl,
      },
    ],
    colors: [
      {
        name: "Red",
        cloudinaryPublicId: "red-cloudinary-id",
        cloudinaryUrl: "red-cloudinary-url",
      },
      // Add more colors if needed
    ],
    brands: [getRandomElement(brands)._id],
    options: [
      {
        name: "Size",
        values: [
          {
            value: "Small",
            image: "size-small-image-url",
            price: 0,
          },
          // Add more size options if needed
        ],
      },
      // Add more options if needed
    ],
    countryOfOrgin: "Country",
    shopId: getRandomElement(shops)._id,
    shop: getRandomElement(shops),
  };

  const product = await Product.create(productData);
  console.log(`Product ${product.name} created with ID: ${product._id}`);
};

const seedProducts = async () => {
  // Retrieve all shops, categories, and brands from the database
  const shops = await Shop.find({});
  const categories = await Category.find({});
  const brands = await Brands.find({});

  // Generate about 1000 products
  const productPromises = Array.from({ length: 1000 }, () =>
    generateProductData(shops, categories, brands)
  );
  await Promise.all(productPromises);

  console.log("All products created successfully!");

  mongoose.connection.close();
};

seedProducts();
